spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: websocket-service
          uri: lb:ws://websocket-service
          predicates:
            - Path=/ws/**
          filters:
            - name: CustomFilter
#            - RewritePath=/ws/(?<segment>.*), /ws

server:
  port: 8000
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: DEBUG
