spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: websocket-service
          uri: lb:ws://websocket-service
          predicates:
            - Path=/ws/**
          filters:
            - name: GlobalFilter
#      loadbalancer:
#        instances:
#          websocket-service:
#            - uri: ws://localhost:9001
#            - uri: ws://localhost:9002

server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: DEBUG
